### ISSUE TITLE
How to run the test_project

### ISSUE THREAD

**Issue by typonaut** [lvm/django-eav2#203]
If I try to run the test_project  (```manage.py runserver```) I get the error:

```AttributeError: 'Settings' object has no attribute 'ROOT_URLCONF'```

But there is no ```urls.py``` in the project!?

**Comment by Dresdn** [comment]
The test project does not have any UI, URLs, etc., so `manage.py runserver` isn't going to work. Instead, you can interact with the models from the CLI via `manage.py shell`.

Linking this to #93 as instructions to run the test project should be included in the docs.
