### ISSUE TITLE
Running test project

### ISSUE THREAD

**Issue by typonaut** [lvm/django-eav2#306]
Could someone perhaps outline how the test project is envisaged to fit together?

**Comment by Dresdn** [comment]
Could you explain in more detail what you mean by "fit together"?

I recognize there isn't any development documentation, so if you'd like to run/use the test project, here are the steps to do so:

1. Ensure Poetry supports 2.0 version (v1.2.2 or 1.3)
2. Install project with `poetry install`
3. Migrate `poetry run ./manage.py migrate`
4. Run the shell `poetry run ./manage.py shell`

The project is really used to demonstrate how to use the application.

Does that help?

**Comment by typonaut** [comment]
I am not clear what I am gaining running ```poetry run ./manage.py shell``` rather than ```python ./manage.py shell```.

But, that, I think, is not really the issue. Rather, if we look at the models, there is ```Doctor```, ```Patient``` and ```Encounter```. Of these three, only ```Doctor``` has an ```@register_eav``` decorator.  At this point I am thinking that the most logical model to have EAV elements is ```Patient```, but that does not appear to be what is intended.

Then I explore a little further, to find that ```Patient``` has a foreign key to ```ExampleModel``` (which does have an ```@register_eav``` decorator), and that ```M2MModel``` (with ```@register_eav```) has a many-to-many link to ```ExampleModel``` (and I have a ```test_project_m2mmodel_models``` table in my database).

```Encounter``` also has a foreign key to ```Patient```. It is not obvious to me what goes in ```Encounter.num```.

So, I suspect that ```Patient``` gets attributes from ```eav.Attribute``` via ```ExampleModel``` and ```M2MModel```, but not sure how that happens.

I can also see that there is an ```eav.forms.BaseDynamicEntityForm``` class, which manages the EAV entities in a form… but that seems to require the ```@register_eav``` on the model, which ```Patient``` does not have.

Then there are a couple of other models, ```ExampleMetaclassModel``` and ```RegisterTestModel```, that I have no idea the function of, but imply that the ```.name``` field relates to the ```name``` of an attribute.

Sorry for being a neophyte, but just not quite getting it, and without documentation it is difficult to fathom.

**Comment by Dresdn** [comment]
> I am not clear what I am gaining running `poetry run ./manage.py shell` rather than `python ./manage.py shell`.

This was specifically around my comment stating if you'd like to run the project and play with it via shell.

> But, that, I think, is not really the issue. Rather, if we look at the models, there is `Doctor`, `Patient` and `Encounter`. Of these three, only `Doctor` has an `@register_eav` decorator. At this point I am thinking that the most logical model to have EAV elements is `Patient`, but that does not appear to be what is intended.
> 
> Then I explore a little further, to find that `Patient` has a foreign key to `ExampleModel` (which does have an `@register_eav` decorator), and that `M2MModel` (with `@register_eav`) has a many-to-many link to `ExampleModel` (and I have a `test_project_m2mmodel_models` table in my database).
> 

The `test_project` is used as a basis for the tests. What I would suggest is to take a look at the various tests and see how they use the test project. For example, `test_project.models.Patient` is purposely not registered in the `models.py` as it's registered within the test itself.

The short of it is that any model can be registered to have the EAV attributes associated with it. Those attributes can be controlled by creating your own `EavConfig`, as shown in my comment https://github.com/jazzband/django-eav2/issues/307#issuecomment-1406979635

> Sorry for being a neophyte, but just not quite getting it, and without documentation it is difficult to fathom.

No need to apologize, everyone is at one point! And yes, documentation should be improved, but we all know where that falls on the priority list at times.

I hope this helps!
