### ISSUE TITLE
Linking model instance to subset of attributes

### ISSUE THREAD

**Issue by typonaut** [lvm/django-eav2#307]
I can see in the issues history that there was a PR to enable different attributes for different model instances, but I cannot see any documentation on how to implement that feature.

Thanks.

**Comment by Dresdn** [comment]
Which PR are you referring to?

My initial suggestion would be to look at overriding `eav.registry.EavConfig.get_attributes()`. From there, you can return attributes based on some criteria.

**Comment by Dresdn** [comment]
Realized I should add some code in case this is in alignment with what you're thinking.

Let's say there's a `Doctor` and `Patient` model where you'd want a Patient to have different attributes depending on the Doctor. In that case, you could create your models like this:

```
class Doctor(models.Model):
  attributes = models.ManyToManyField(eav.models.Attribute)

class Patient(models.Model):
  doctor = models.ForeignKey(Doctor)

class PatientConfig(EavConfig):

    @classmethod
    def get_attributes(cls, instance=None):
        try:
            doctor = instance.doctor
        except AttributeError:
            return Attribute.objects.none()

        return doctor.attributes.all()

eav.register(Patient, PatientConfig)
```

Hope this helps.

**Comment by typonaut** [comment]
Actually, my mistake on that, the issue #40 was actually about linking a subset of attributes to a model, rather than to an instance/single record of that model.

Thanks for your example.
