### ISSUE TITLE
Error description about `TYPE_ENUM`

### ISSUE THREAD

**Issue by 954-Ivory** [lvm/django-eav2#309]
https://github.com/jazzband/django-eav2/blob/789f53bcc5a6156b08322b75f2ea0e32b3d7814e/eav/models.py#L191

This field only supports single selection.
Maybe we shoud change to it to `Select` or `Enum Choice`?

**Comment by Dresdn** [comment]
Technically, `TYPE_ENUM` could be rendered as `<select>` or `<select multiple>`, so I'd agree that `Multiple Choice` is probably inaccurate.

If it would help be more clear, maybe `Select` makes more sense of the options proposed.

**Comment by 954-Ivory** [comment]
> Technically, `TYPE_ENUM` could be rendered as `<select>` or `<select multiple>`, so I'd agree that `Multiple Choice` is probably inaccurate.
> 
> If it would help be more clear, maybe `Select` makes more sense of the options proposed.

Should we create a new `Attribute` named `TYPE_CHECKBOX` to support multiple choice?

I have created similar fields in my own project.
But I used monkey patch to support `dynamic choices`, it is little dirty.

**Comment by Dresdn** [comment]
I don't think we need a new type as we already have a class for that: `EnumGroup`

Looking at it again, instead of "Multiple Choice", it should be the "value" - so how would you describe that? "Characters"? "String"? "Value"? "Multiple Choice Value"?

The `EnumGroup` is really the "Multiple Choice" select with `Enum` being a `CharField` value.

What do you think?

**Comment by 954-Ivory** [comment]
I think `EnumGroup` is the options of `TYPE_ENUM`.

My English is poor, so I show it with this:

```python
class Book(models.Model):
    name = models.CharField(max_length=128),
    ...

eav.register(Book)

cs = EnumValue.objects.create(value='Computer science')
se = EnumValue.objects.create(value='Software engineering')
cn = EnumValue.objects.create(value='Computer network')

btg = EnumGroup.objects.create(name='book tags group')
btg.values.add(cs)
btg.values.add(se)
btg.values.add(cn)

Attribute.objects.create(
    name='tags', datatype=Attribute.TYPE_ENUM, enum_group=btg
)
```

---

The `TYPE_ENUM` can only select single option:

```python
# single option
Book.objects.create(
    name='Computer Networking A Top Down Approach',
    eav__tags=cs,
)
```

```html
<--widget-->
<select>
  <option>Computer science</option>
  <option>Software engineering</option>
  <option>Computer network</option>
</select>
```

---

The `TYPE_CHECKBOX` can support this:
```python
# mutiple option
Book.objects.create(
    name='Computer Networking A Top Down Approach',
    eav__tags=[cs,cn],
)
```
```html
<--widget-->
<div>
  <input type="checkbox">
  <label>Computer science</label>
</div>
<div>
  <input type="checkbox">
  <label>Software engineering</label>
</div>
<div>
  <input type="checkbox">
  <label>Computer network</label>
</div>
```

**Comment by Dresdn** [comment]
My apologies as I can see how my prior comment could be confusing for non-native English speakers.

I completely agree with what you said and put into code.

I was curious and pulled up the HTML select tag, and we could call it either "Value" or "Option" for consistency.

**Comment by 954-Ivory** [comment]
What do we need to do next?

**Comment by Dresdn** [comment]
Honestly, probably nothing. In my prior response, I was thinking about the completely wrong thing. Leaving it as "Multiple Choice" in English works well as it can be implied you can choose a single value or multiple values, depending on how you render the display.

I'll close this out unless someone has a better idea, and I'll get your PR done.
