### ISSUE TITLE
Failing to install with django 4.2.3

### ISSUE THREAD

**Issue by Tobi-De** [lvm/django-eav2#383]
Currently, the latest version of the package is 1.3.1. However, attempting to install it alongside Django 4.2 is not possible using pip due to a dependency conflict. The error message I encountered is as follows:

```shell
django-eav2 1.3.1 requires django<4.2,>=3.2, but you have django 4.2.3 which is incompatible.
```

Upon reviewing the pyproject.toml file, I noticed that the Django version is actually restricted to 4.3. To resolve this issue, it would be sufficient to release a new version of the package that includes the currently specified dependencies. Thank you.

**Comment by Dresdn** [comment]
Good call out. I'll release a new version now. Let me know if there's any issues @Tobi-De

**Comment by Dresdn** [comment]
1.4.0 is released
