### ISSUE TITLE
TypeError: Cannot combine a unique query with a non-unique query.

### ISSUE THREAD

**Issue by masarliev** [lvm/django-eav2#395]
Filtering by 3 or more attributes raises  TypeError: Cannot combine a unique query with a non-unique query.
Example:  Patient.objects.filter(eav__fever=self.yes, eav__city='Nice', eav__age=3)

**Comment by dasith2190** [comment]
I had the same issue. Any update on this?

**Comment by dasith2190** [comment]
The issue seems to be in the eav_filter function. If `nkwargs[nkey] = (nkwargs[nkey].distinct() & nval.distinct()).distinct()` is changed to `nkwargs[nkey] = (nkwargs[nkey].distinct() & nval.distinct()).distinct()` it seems to fix it. If someone could update it, it would be greatly appreciated.


```

def eav_filter(func):
    @wraps(func)
    def wrapper(self, *args, **kwargs):
        nargs = []
        nkwargs = {}

        for arg in args:
            if isinstance(arg, Q):
                # Modify Q objects (warning: recursion ahead).
                arg = expand_q_filters(arg, self.model)
                # Rewrite Q-expression to safeform.
                arg = rewrite_q_expr(self.model, arg)
            nargs.append(arg)

        for key, value in kwargs.items():
            # Modify kwargs (warning: recursion ahead).
            nkey, nval = expand_eav_filter(self.model, key, value)

            if nkey in nkwargs:
                # Apply AND to both querysets.
                nkwargs[nkey] = (nkwargs[nkey].distinct() & nval.distinct()).distinct()
            else:
                nkwargs.update({nkey: nval})

        return func(self, *nargs, **nkwargs)

    return wrapper

```

**Comment by Dresdn** [comment]
More than happy to take a PR @dasith2190. I started to take a look at it and started with writing a test within `test_queries.py`:

```
    def test_filter_with_multiple_eav_attributes(self):
        # Initialize data
        self.init_data()

        # Use the filter method with 3 EAV attribute conditions
        patients = Patient.objects.filter(
            eav__age=3,
            eav__city='New York',
            eav__fever='no',
        )

        # Assert that the expected patients are returned
        self.assertEqual(len(patients), 1)
        self.assertEqual(patients[0].name, 'Anne')
```

Note that with your change, the test doesn't pass.

**Comment by dasith2190** [comment]
Hi @Dresdn,

Thank you for the response!

I was looking into it a little bit more. When I run the test with 2 params and with the original code, it returns 0 results. Im not sure if the fix below is the best way to address it but this should fix the problem.

```
    @wraps(func)
    def wrapper(self, *args, **kwargs):
        nargs = []
        nkwargs = {}

        for arg in args:
            if isinstance(arg, Q):
                # Modify Q objects (warning: recursion ahead).
                arg = expand_q_filters(arg, self.model)
                # Rewrite Q-expression to safeform.
                arg = rewrite_q_expr(self.model, arg)
            nargs.append(arg)

        for key, value in kwargs.items():
            # Modify kwargs (warning: recursion ahead).
            nkey, nval = expand_eav_filter(self.model, key, value)

            if nkey in nkwargs:
                # Add filter to check if matching entity_id is in the previous queryset with same nkey
                nkwargs[nkey] = nval.filter(entity_id__in=nkwargs[nkey].values_list('entity_id', flat=True)).distinct()
            else:
                nkwargs.update({nkey: nval})

        return func(self, *nargs, **nkwargs)

    return wrapper
```

**Comment by Dresdn** [comment]
Thanks for the effort @dasith2190. The resulting SQL isn't super optimized, but without a major rework of `eav.queryset.expand_eav_filter()`, this is a good solution.

@masarliev - Your query now works as expected, with a slight tweak to use the `self.no` value:

`Patient.objects.filter(eav__fever=str(self.no), eav__city='Nice', eav__age=3)`

I can't think of anything else to enhance the test, so if you all think it looks good, we can merge #414 in.

**Comment by dasith2190** [comment]
Hi @Dresdn, the pull request looks good. Thank you!
