### ISSUE TITLE
Provide UUIDField option for pk field and a natural key feature for serialization

### ISSUE THREAD

**Issue by mathiasag7** [lvm/django-eav2#427]
Provide a general summary of the issue in the title above.

## Detailed Description
I have come with a project where I was obliged to fork the package and integrate some features to make it work as expected for the project. Instead of creating a new package, we suggest that you use these ideas with your teams to make it available for everybody. If needed, I can help too since I have already implemented it in a project. The features include the a natural key possibility when it come to serialization and also the ability to specify the primary key field type, such as using UUIDField instead of IntegerField. This will make a big advancement.

**Comment by Dresdn** [comment]
That sounds great @mathiasag7. PRs are always welcome! Since this is an open project, no need to ask for permission.
