### ISSUE TITLE
Hello, I just wanted to inform you that this version of django eav is not yet available to be installed directly with pip in a project.

### ISSUE THREAD

**Issue by mathiasag7** [lvm/django-eav2#451]
Hello, I just wanted to inform you that this version of django eav is not yet available to be installed directly with pip in a project.

_Originally posted by @mathiasag7 in https://github.com/jazzband/django-eav2/issues/428#issuecomment-1792831271_

**Comment by Dresdn** [comment]
I will create a release later today.

**Comment by mathiasag7** [comment]
ok thanks.

**Comment by Dresdn** [comment]
[1.5.0 is released](https://github.com/jazzband/django-eav2/releases/tag/1.5.0)

**Comment by mathiasag7** [comment]
thanks.
