### ISSUE TITLE
Docs Build Failing

### ISSUE THREAD

**Issue by Dresdn** [lvm/django-eav2#93]
Docs [builds are failing](https://readthedocs.org/projects/django-eav2/builds/).

Might be a good time to update/refresh the docs using the [latest template](https://github.com/readthedocs/tutorial-template/tree/main/docs).

**Comment by ianrosedev** [comment]
If this is something you need help with, I'm down to do it.
I just found this project recently, so I'm not 100% sure how issues are handled.

**Comment by Dresdn** [comment]
@ianrosedev - more than happy to accept PRs!

**Comment by ianrosedev** [comment]
If someone has time to knock this out before I can, please go for it.

Sorry, I ended up being busy for the foreseeable future.
